# Generated by Django 6.0.2 on 2026-02-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_course_course_detail_course_course_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_photo',
            new_name='Course_photo',
        ),
    ]
